import os
from typing import *

from pyutil import IOUtils


class File:

    def __init__(self, path, is_append: bool = False):
        self.path = path
        self.content = ""
        self.is_append = is_append
        if self.is_append:
            if os.path.isfile(path):
                self.content = IOUtils.load(path, "txt")
        # end ifl, if

    def append(self, line: str, is_line_end: bool = True) -> "File":
        self.content += line
        if is_line_end:
            self.content += "\n"
        # end if
        return self

    def append_comment(self, line: str) -> "File":
        self.content += "%% " + line + "\n"
        return self

    def save(self) -> None:
        content = self.content
        if not self.is_append:
            content = self.autogen_notice() + content
        # end if
        IOUtils.dump(self.path, content, "txt")
        return

    @classmethod
    def autogen_notice(cls) -> str:
        return "%% Automatically generated by pyutil.latex \n"
